# Generated by Django 3.2.3 on 2021-10-30 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_No', models.IntegerField()),
                ('Name', models.CharField(max_length=50)),
                ('Contact_No', models.CharField(max_length=10)),
                ('Email', models.CharField(max_length=50)),
            ],
        ),
    ]
